### ISSUE TITLE
Ping Heroku regularly so that it doesn't have to boot all the time

### ISSUE THREAD

**Issue by raucao** [AfricaHackTrip/simple-speed#15]
The sample transfers are done to/from Heroku, a PaaS, where `server.rb` is running on. The problem is that they stop the app when there's no request for a certain time, and restart it on the next request then. But restarting is terribly slow, so the first sample after a restart will always take 2 sample runs (20 seconds) instead of 1.

We should have a cron job running somewhere that does a request every 5 minutes or sth, so that the app isn't being stopped anymore.

**Comment by bumi** [comment]
I think you can use some monitoring tool like pingdom to do that.

**Comment by raucao** [comment]
Crazy expensive. I don't even have free slots left on my account.

Thing is, we don't need to do it from various locations with test results and all. A simple cron job that curls a URL is perfectly fine.

**Comment by bumi** [comment]
ah, thought they still have one check for free then you would not need to maintain a job or a second app to do it. :)

**Comment by raucao** [comment]
I set up a cron job that does a request to `/upload` every 5 minutes. Should be enough.
