### ISSUE TITLE
Change background colour of the progress areas

### ISSUE THREAD

**Issue by lukehefson** [AfricaHackTrip/simple-speed#17]
I'd really like the background of the progress area to have the colour #a7c1bc (rgb 167, 193, 188) like so:

![screen shot 2013-10-24 at 00 22 00](https://f.cloud.github.com/assets/1469659/1394433/52897d3e-3c29-11e3-9ae3-7bdb1d981289.png)

…but I'm struggling with the CSS for it. What's the solution?

**Comment by raucao** [comment]
Fixed the hacky implementation, so that we can use exact color values for all elements now. Changed the background color already.
