### ISSUE TITLE
The 'Start test' button should click and not disappear

### ISSUE THREAD

**Issue by lukehefson** [AfricaHackTrip/simple-speed#18]
Can we add an on-click `a:active` state to the 'Start test' button and stop it from disappearing during the test?

**Comment by lukehefson** [comment]
More on my logic:

'Start test' is definitely a button and I don't think that a button should ever disappear. Obviously it shouldn't be left enabled if it's going to break the test itself, so I can imagine a couple of solutions:
1. Hitting the start test button again cancels the current test and starts a new test. This would be my ideal solution but I can appreciate that it may be hard to implement.
2. The button gets disabled after being clicked and then re-enabled once the test has finished. We'd need to come up with a nice disabled state for the button, perhaps with the text in the button changing to `Test in progress…`?

What do you think @skddc?

**Comment by raucao** [comment]
Yes, I'd like to implement option 2. I agree that it makes more sense than just hiding it. We can still look into cancelling tests later and change the button behavior then.

**Comment by lukehefson** [comment]
Great. I'll work on a state for it.

**Comment by lukehefson** [comment]
Here's some mocks for those states.

Clicked state:

![screen shot 2013-10-25 at 14 23 06](https://f.cloud.github.com/assets/1469659/1407273/26abed56-3d68-11e3-8dda-7569031687cf.png)

Disabled state:

![screen shot 2013-10-25 at 14 23 19](https://f.cloud.github.com/assets/1469659/1407274/3161c96e-3d68-11e3-82e7-62aa0d356fbb.png)

**Comment by raucao** [comment]
I like it.

**Comment by raucao** [comment]
Done.
