### ISSUE TITLE
Submit to Firefox Marketplace

### ISSUE THREAD

**Issue by raucao** [AfricaHackTrip/simple-speed#19]

**Comment by raucao** [comment]
Just submitted the app, and it's pending review now: https://marketplace.firefox.com/app/simple-speed/

Add your comments or reopen if something's wrong or missing. Also, tell me your email addresses, if you want me to add you as collaborators on the marketplace.

**Comment by raucao** [comment]
@lukehefson Could you (as native English speaker) have a look at the description maybe?

**Comment by sharmake** [comment]
That's cool!
abdinoorjr@gmail.com

**Comment by raucao** [comment]
@sharmake You need to create an account on http://marketplace.firefox.com/ first.

**Comment by sharmake** [comment]
Ok! Will do that....

**Comment by lukehefson** [comment]
My email address is luke at github dot com.

I'm getting "Oh no! The app requested is not public." when trying to view the listing. I checked out http://marketplace.firefox.com/ but I'm still not sure how to sign up?!?

**Comment by raucao** [comment]
You can only see the listing when you're listed as a developer of that app, until the listing is reviewed by the Marketplace team.

There's a sign-in link in the top right corner.

**Comment by sharmake** [comment]
Already created an account...... @Basti

**Comment by lukehefson** [comment]
@skddc Cool, let me know when it's reviewed and I'll check the description

**Comment by raucao** [comment]
@sharmake Don't know why, but I can't add you with that address.

**Comment by sharmake** [comment]
Neither do I.......... i signed up with abdinoorjr@gmail.com with a display
name abdinoorjr

**Comment by raucao** [comment]
> A user with that email address does not exist, or the user has not yet accepted the developer agreement.

Maybe the latter is the case?

**Comment by raucao** [comment]
\o/

https://marketplace.firefox.com/app/simple-speed/

Log in and rate the app!
