### ISSUE TITLE
Test files not big enough for good connections

### ISSUE THREAD

**Issue by raucao** [AfricaHackTrip/simple-speed#23]
Just came back to Europe, and on this connection the testfiles are transferred much faster than in 10 seconds. :)

So we need larger test files.

**Comment by raucao** [comment]
Working properly with 30-40 Mb/s down and 10 up for me now.

![screen shot 2013-10-31 at 12 26 39 pm](https://f.cloud.github.com/assets/842/1445722/25107894-4228-11e3-85ec-2e5747d6d06e.png)

By the way, I just compared the numbers with 2 of the big speed test sites, and they were pretty much the same. Maybe even more correct.

**Comment by sharmake** [comment]
That's cool....
