### ISSUE TITLE
Rename the repo

### ISSUE THREAD

**Issue by lukehefson** [AfricaHackTrip/simple-speed#3]
@skddc Can we rename the repo to `simple-speed`?

**Comment by raucao** [comment]
We can, but then everybody has to change their Git remote configuration. Should I do it?

**Comment by lukehefson** [comment]
Yeah that is a pain. Let's not bother then unless @bavoni @sharmake @mussa-kimolo @owgee don't mind.

**Comment by bavoni** [comment]
I don't mind.

**Comment by owgee** [comment]
That's ok.

**Comment by raucao** [comment]
Ok, will rename then.

You can change it on your machines with sth like `git remote set-url origin {new_url}`

**Comment by raucao** [comment]
Done.
