### ISSUE TITLE
Create nice app icon

### ISSUE THREAD

**Issue by raucao** [AfricaHackTrip/simple-speed#6]
We need a nice app icon for home screens and app dashboards. It should be square format and at least 512x512px.

**Comment by owgee** [comment]
Okay,will do it as soon as possible.

**Comment by raucao** [comment]
Cool!

**Comment by lukehefson** [comment]
I just submitted a pull request with an icon I threw together in 10 minutes:

https://github.com/AfricaHackTrip/speedy-speed-test/commit/744a96acb8e6a1a127e7a60739de84228dff2666

But @owgee, I'm sure you can do much better than me!

**Comment by owgee** [comment]
My photoshop is painfully slow.Will add another icon though..I saw yours,it's not bad

**Comment by raucao** [comment]
I just uploaded this one to 5apps, so it should be used by all install mechanisms and as favicon now:

![simplespeed-icon](https://f.cloud.github.com/assets/842/1415504/c924b954-3f08-11e3-8d6c-716c711f4338.png)

**Comment by raucao** [comment]
We should probably still optimize the form for iOS, so that they don't apply the black background. Closing this issue for now, though. Let's open a separate one if we decide to improve specific things.
